definitions:
  types.Pong:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Pong'
      summary: ping example
      tags:
      - example
  /api/v2/ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Pong'
      summary: ping example
      tags:
      - example
swagger: "2.0"
